### ISSUE TITLE
Better SDCC

### ISSUE THREAD

**Issue by funlw65** [AguHDz/PicPas-Librerias_y_Programas#1]
SDCC at 3.7.0 is a little better - smaller code. Will you redo the tests?

**Comment by AguHDz** [comment]
Thank you for the notice!
Of course I will test it on report the results.

**Comment by AguHDz** [comment]
The new version 3.7 has not obtained any progress in the test.  :( 
SDCC 3.7 (RAM: 45 bytes / FLASH: 1871 words) : 1916
SDCC 3.6 (RAM: 43 bytes / FLASH: 1842 words) : 1885

**Comment by funlw65** [comment]
Wow, that is not good... other type of microcontrollers have much better support (e.g. stm8) :( 
Thank you for the test!
